name: pdf_export_print_example
description: PDF Export Print library example application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # 依赖主库
  pdf_export_print:
    path: ../
  
  # UI相关
  cupertino_icons: ^1.0.8
  
  # PDF相关
  printing: ^5.14.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
