name: pdf_export_print
description: A powerful and highly customizable Flutter PDF generation library with modular design.
version: 1.0.0
homepage: https://github.com/example/pdf_export_print
repository: https://github.com/example/pdf_export_print
issue_tracker: https://github.com/example/pdf_export_print/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.3
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  # 字体资源配置（用于PDF中文显示）
  assets:
    - assets/fonts/

  # 字体family声明（精简版：仅保留Regular和Bold）
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: assets/fonts/AlibabaPuHuiTi-3-55-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlibabaPuHuiTi-3-85-Bold.ttf
          weight: 700